.\" man: Bash-Utils Documentation
.\" man-name: bash-utils
.\" author: Pierre Cassat
.\" section: 7
.\" date: 2015-08-09
.\" version: 0.0.1
.TH  "bash-utils" "7" "2015-08-09" "Version 0.0.1" "Bash-Utils Documentation"
.SH USAGE
.PP
To create a script using the library, you can call the \fImodel\fP argument of the library itself, which
will create a starter template script:
.RS

.EX
bash-utils.bash model /path/to/your/script.sh
.EE
.RE
.PP
Actually, the only requirement to use the library is to source it in your script:
.RS

.EX
source bash-utils.bash
.EE
.RE
.SS Notes about \fIbash\fP scripting and usage
.PP
To enable "per-user" binaries (let the system look in any `\fS$HOME/bin/\fP` directory when searching scripts), 
be sure to add that directory to the `\fS$PATH\fP` environment variable (in your `\fS$HOME/.bashrc\fP` for instance):
.RS

.EX
# user binaries path
.br
[ -d "${HOME}/bin" ] && export PATH="${PATH}:${HOME}/bin";
.EE
.RE
.PP
You can name your scripts following your preferences and place it where you want as long as you can access it easily.
The file extension has no incidence upon the script's type (\fIbash\fP in our case) as the interpreter is designed by the 
\fBshebang\fP directive <https://en.wikipedia.org/wiki/Shebang_%28Unix%29> ; you could name your script with an 
`\fS.sh\fP`, a `\fS.bash\fP` and even a `\fS.py\fP` extension (which would have no real sense here) or let it without extension 
at all with no difference.
.PP
A command-line program (such as a shell script) often accepts to set some options and arguments calling it in a terminal
or another script. A global synopsis of command line call can be:
.RS

.EX
program-to-run -o --option='my value' --option-2 'my value' argument1 argument2
.EE
.RE
.PP
The rules are the followings:
.RS
.IP \(bu 
an \fIargument\fP is a setting passed to the script when calling it ; the arguments are not the same as the options as 
they are not named but identified by their position ; i.e. `\fS./script --option argument1 argument2\fP`
.IP \(bu 
\fIoptions\fP are various settings passed to the script when calling it ; each option is prefixed by one or more dash `\fS-\fP` 
and can have an argument ; by convention, a short option is composed by one single letter prefixed by one dash, i.e. `\fS-o\fP`, 
and a long option is composed by a word prefixed by two dashes, i.e. `\fS--option\fP` ; when an option accepts an argument, 
it must be separated from the option name by an equal sign, i.e. `\fS--option=argument\fP` and `\fS-o=argument\fP` ; i.e. 
`\fS./script -o --option-with-no-arg --option-with-arg=argument_value\fP`
.RE
.SS Starter template
.RS

.EX
#!/usr/bin/env bash
.br
source ~/bin/bash-utils.bash
.br

.br
# write your scripts logic here
.br
# ...
.br

.br
# a script should always return a status
.br
exit 0
.EE
.RE
.SS Customize your script
.PP
To build your own command, you may first override informational variables:
.RS

.EX
CMD_NAME=...
.br
CMD_VERSION=...
.br
CMD_COPYRIGHT=...
.br
CMD_LICENSE=...
.br
CMD_SOURCES=...
.br
CMD_DESCRIPTION=...
.br
CMD_SYNOPSIS=...
.br
CMD_HELP=...
.br
CMD_OPTS_SHORT=...
.br
CMD_OPTS_LONG=...
.EE
.RE
.PP
Then you can customize script's options (see below) to fit your needs and write your script's logic in the last
part of the model.
.SH DOCUMENTATION
.SS Library's methods
.PP
The library embeds a short set of methods to facilitate your scripts:
.RS
.IP \(bu 
the `\fSdie()\fP` method will exit with an error message and a back trace, all to STDERR
.IP \(bu 
the `\fSerror()\fP` method will exit with an error message to STDERR (user friendly)
.IP \(bu 
the `\fSwarning()\fP` method will write an error message to STDERR (without exiting the script)
.IP \(bu 
the `\fStry()\fP` method will emulate a \fItry/catch\fP process by calling a sub-command catching its result
.RE
.PP
Errors are handled by the `\fSdie()\fP` method (using the \fItrap\fP built-in command).
.PP
Exits are handled by the `\fScleanup()\fP` method (using again the \fItrap\fP built-in command). You can add in this method 
any cleanup you want to be done when the script exits.
.PP
A special \fIoptions\fP and \fIarguments\fP handling is designed to rebuild the input command and follow special treatments
for default options and arguments. To use this, add in your script:
.RS

.EX
rearrange_options "$@"
.br
[ -n "$CMD_REQ" ] && eval set -- "$CMD_REQ";
.br
common_options "$@"
.br
common_arguments "$*";
.EE
.RE
.PP
You can \fBoverwrite any method\fP by re-defining it after having sourced the library:
.RS

.EX
source .../bash-utils.bash
.br

.br
error() {
.br
    # your custom error handler
.br
}
.EE
.RE
.PP
The best practice is to create user methods instead of overwrite native ones and call them:
.RS

.EX
source .../bash-utils.bash
.br

.br
user_error() {
.br
    # your custom error handler
.br
}
.br

.br
[ -f filename ] || user_error 'file not found';
.EE
.RE
.SS Colorized output
.PP
The library embeds a `\fSe_color()\fP` method you can use to output some colorized contents. It allows you
to construct you content with XML-like tags. For instance:
.RS

.EX
CTT="this is a content with <bold>tags</bold> to <red>play with</red> <cyan_bg>output</cyan_bg>"
.EE
.RE
.PP
The lists of available text styles and colors are stored in the `\fSTEXTOPTIONS\fP` and `\fSTEXTCOLORS\fP` environment variables.
.SS Script's options
.PP
Default options handled by the library are:
.RS
.IP \(bu 
\fB-q\fP | \fB--quiet\fP: enables the `\fS$QUIET\fP` environment variables ; this should decrease script's output (only errors or
required output should be returned) ; this options disables the `\fS$VERBOSE\fP` environment variable
.IP \(bu 
\fB-v\fP | \fB--verbose\fP: enables the `\fS$VERBOSE\fP` environment variable ; this should increase script's verbosity (inform
user about what is happening) ; this options disables the `\fS$QUIET\fP` environment variable
.IP \(bu 
\fB-f\fP | \fB--force\fP: enables the `\fS$FORCE\fP` environment variable ; this should let the user to choose all default behaviors
in case a choice is required (no prompt running the script)
.IP \(bu 
\fB-x\fP | \fB--debug\fP: enables the `\fS$DEBUG\fP` environment variable ; this should drastically increase script's verbosity
(verbosity should be one level more than in `\fS$VERBOSE\fP` mode)
.IP \(bu 
\fB--dry-run\fP: enables the `\fS$DRY_RUN\fP` environment variable ; this should not de sensible stuff but inform user about
what should be done
.RE
.PP
These options are handled by the \fIgetopt\fP program. You can add your own options by overriding the following variables:
.RS

.EX
CMD_OPTS_SHORT='fqvx'
.br
CMD_OPTS_LONG='debug,dry-run,force,quiet,verbose'
.EE
.RE
.PP
By default, the `\fScommon_options()\fP` method will throw en error if an unknown option is met. You can avoid this behavior
by prefixing the `\fSCMD_OPTS_SHORT\fP` by a colon `\fS:\fP`.
.PP
For each option added, you MUST define your own treatment for it in a parsing loop:
.RS

.EX
CMD_OPTS_SHORT=':fqvxo:'
.br
CMD_OPTS_LONG='debug,dry-run,force,quiet,verbose,my-option'
.br
while [ $# -gt 0 ]; do
.br
    case "$1" in
.br
        # do not throw error for common options
.br
        -f | -q | -v | -x | --force | --quiet | --verbose | --debug | --dry-run ) true;;
.br
        # user option
.br
        -o | --my-option )
.br
            OPTARG="$(echo "$2" | cut -d'=' -f2)"
.br
            MYVAR="${OPTARG:-default}"
.br
            shift
.br
            ;;
.br
    esac
.br
    shift
.br
done
.EE
.RE
.PP
In your script, you can use a flag like:
.RS

.EX
$FLAG && ...; # do something when FLAG is ENABLED
.br
$FLAG || ...; # do something when FLAG is DISABLED
.EE
.RE
.PP
Due to known limitations of the \fIgetopt\fP program, you should always use an equal sign between 
an option (short or long) and its argument: `\fS-o=arg\fP` or `\fS--option=arg\fP`.
.SS Script's arguments
.PP
The library handles by default the following arguments:
.RS
.IP \(bu 
\fBversion\fP to get the name and version number of the script
.IP \(bu 
\fBabout\fP to get a long information string about the script (license, sources ...)
.IP \(bu 
\fBhelp\fP to get the full help information of script's usage
.IP \(bu 
\fBusage\fP to get the short help information of script's usage (its \fIsynopsis\fP).
.RE
.PP
The output of the informational arguments listed above are constructed using the `\fSCMD_...\fP` environment
variables you may define for each script.
.PP
You can define your own arguments by overriding the `\fScommon_arguments()\fP` method or build a new loop
over script's arguments:
.RS

.EX
case "$1" in
.br
    arg) ... ;;
.br
esac
.EE
.RE
.SS Technical points
.PP
The library uses the following \fIBash\fP options by default:
.RS
.IP \(bu 
`\fS-e\fP`: exit if a command has a non-zero status
.IP \(bu 
`\fS-E\fP`: trap on ERR are inherited by shell functions
.IP \(bu 
`\fS-o pipefail\fP`: do not mask pipeline's errors
.IP \(bu 
`\fS-u\fP`: throw error on unset variable usage
.IP \(bu 
`\fS-T\fP`: trap on DEBUG and RETURN are inherited by shell functions
.RE
.PP
To make robust scripts, here are some reminders:
.RS
.IP \(bu 
to use a variable eventually unset: `\fSecho ${VARIABLE:-default}\fP`
.IP \(bu 
to make a silent sub-command call: `\fSval=$(sub-command 2>/dev/null)\fP`
.RE
.SH SEE ALSO
.PP
Online \fIbash\fP scripting guides and tools:
.RS
.IP \(bu 
the \fIBash Guide for Beginners\fP: <http://tldp.org/LDP/Bash-Beginners-Guide/html/index.html> (recommended) 
.IP \(bu 
the \fIAdvanced Bash-Scripting Guide\fP: <http://tldp.org/LDP/abs/html/index.html> (recommended) 
.IP \(bu 
the \fIBash Reference Manual\fP at gnu.org: <http://www.gnu.org/software/bash/manual/html_node/index.html>
.IP \(bu 
\fIBATS\fP, a test suite for Bash scripts: <http://github.com/sstephenson/bats>
.RE
.PP
bash(1), bash-utils(1), getopt(1)
