language: c
before_install:
  - sudo add-apt-repository ppa:duggan/bats --yes
  - sudo apt-get update -qq
  - sudo apt-get install -qq bats
script:
  - ./make.sh test
branches:
  only:
    - master
    - dev-modules
notifications:
  email:
    on_success: never