#!/usr/bin/env bash
#
# bash-utils - A *bash* library for better scripting
# <http://gitlab.com/piwi/bash-utils>
# Copyright (c) 2015 Pierre Cassat & contributors
#
# Licensed under the Apache Software Foundation license, Version 2.0;
# you may not use this file except in compliance with the License.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# For sources & updates, see <http://gitlab.com/piwi/bash-utils>.
#
# To transmit bugs, see <http://gitlab.com/piwi/bash-utils/issues>.
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code or see
# <http://www.apache.org/licenses/LICENSE-2.0>.
#
##@!@##

#### BASH OPTIONS ####

# use aliases
shopt -s expand_aliases
# export all modified vars
#set -a
set -o allexport
# match the POSIX 1003.2 standard
set -o posix
# exit if a command has a non-zero status
#set -e
set -o errexit
# do not mask pipeline's errors
set -o pipefail
# trap on ERR are inherited by shell functions
#set -E
set -o errtrace
# trap on DEBUG and RETURN are inherited by shell functions
#set -T
set -o functrace
## throw error on unset variable usage
#set -u
set -o nounset

## for dev usage: debug commands before to execute them
##set -x
#set -o xtrace
## for dev usage: print shell input lines as they are read
##set -v
#set -o verbose

# trap errors to 'die'
trap 'die "trapped error at ${BASH_SOURCE}:${BASH_LINENO:-}:${FUNCNAME:-}()"' 1 2 3 15 ERR
# trap exit to 'shutdown_handler'
trap 'shutdown_handler' EXIT

#### ID ####

readonly BASH_UTILS_NAME='Bash-Utils'
readonly BASH_UTILS_KEY='bash-utils'
readonly BASH_UTILS_VERSION='0.0.1@dev'

#### CORE ####
# functions are written in alphabetical order

# debug environment variables from the `$TO_DEBUG` array
# usage: `debug`
debug()
{
    echo '---- DEBUG ----'
    local length=0
    for i in "${TO_DEBUG[@]}"; do
        [ "${#i}" -gt "$length" ] && length="${#i}";
    done
    for i in "${TO_DEBUG[@]}"; do
        printf "%$((length+1))s : %s\n" "$i" "${!i}"
    done
    echo '---------------'
    return 0
}

# write an internal error on STDERR & exit with status 1
# usage: `die [string='unknown error']`
die()
{
    local err=$?
    [ "$err" -eq 0 ] && err=1;
    if ${QUIET:-false}; then
        echo "${1:-unknown error}" >&2
    else
        {   echo '----'
            echo "**** ${1:-unknown error} ****"
            echo "# exiting with status ${err}"
            echo "# in ${BASH_SOURCE[1]##*/} at line ${BASH_LINENO[0]}"
            echo "# running ${CMD_PID}:${CMD_CALL:-${CMD_CALL_ORIGINAL}}"
            echo "# stack trace:"
            stack_trace
            echo '----'
        } >&2
    fi
    exit "${err:-1}"
}

# write a full error on STDERR & show usage string & exit
# usage: `error [string='unknown error'] [status=1]`
error()
{
    {   echo "error: ${1:-unknown error}"
        $VERBOSE && echo "# in ${BASH_SOURCE[1]##*/} at line ${BASH_LINENO[0]}";
        echo '---'
        usage_info
    } >&2
    exit "${2:-1}"
}

# find an app's module
# usage: `find_module <module_name>`
find_module()
{
    [ $# -lt 1 ] && die 'usage: `find_module <module_name>`';
    local module_name="$1" cmdfile=''
    [ -f "${BASH_UTILS_MODULES}/${module_name}" ] && cmdfile="${BASH_UTILS_MODULES}/${module_name}";
    if [ -n "$cmdfile" ] && [ -f "$cmdfile" ]; then
        echo "$cmdfile" && return 0
    else
        return 1
    fi
}

# test if a function exists - returns a boolean
# usage: `function_exists <func_name>`
function_exists()
{
    [ $# -eq 0 ] && return 1;
    [ "$(type -t "$1")" == 'function' ]
}

# read current `$PATH` values as human readable string
# usage: `get_path`
get_path()
{
    echo -e "$PATH" | tr ':' "\n";
    return 0
}

# test if an app's module exists
# usage: `module_exists <module_name>`
module_exists()
{
    [ $# -lt 1 ] && return 1;
    local module_name="$1" cmd=''
    cmd="$(find_module "$module_name")"
    return $?
}

# load any piped content into `PIPED_INPUT`
# usage: `read_from_pipe [file=/dev/stdin]`
read_from_pipe()
{
    local fpipe fpipedir
    fpipe="${1:-/dev/stdin}"
    fpipedir="$(dirname "$fpipe")"
    if [ -e "$fpipe" ] && [ -p "$fpipe" ]; then
        PIPED_INPUT="$(cat "$fpipe")"
    fi
    export PIPED_INPUT
}

# cleanup after the script exits
# this one should never be called directly as it is trapped on EXIT
# usage: `shutdown_handler`
shutdown_handler()
{
    # draw your own cleanup stuff here
    return 0
}

# get script stack trace
# usage: `stack_trace`
stack_trace()
{
    set +o xtrace
    if [ ${#FUNCNAME[@]} -gt 2 ]; then
        for ((i=1;i<${#FUNCNAME[@]};i++)); do
            echo "  $i: ${BASH_SOURCE[$i+1]:-}:${BASH_LINENO[$i]} ${FUNCNAME[$i]}(...)"
        done
    fi
    return 0
}

# test Bash version required
# usage: `test_bash_version <min_version_number>`
test_bash_version()
{
    local version="$1"
    if [[ ${BASH_VERSION:0:1} -lt $version ]]; then
        warning "you are running an old version of Bash ($BASH_VERSION) - some errors are expected.";
        return 1
    fi
    return 0
}

# try a command and catch errors throwing them to the 'die' function
# from: <http://askubuntu.com/a/53759>
# usage: `try "command"`
try()
{
    local error retval e
    [[ ! "$-" =~ e ]] || e=1
    # Run the command and store error messages (output to the standard error
    # stream in $error, but send regular output to file descriptor 3 which
    # redirects to standard output
    exec 3>&1
    set +e
    error="$("$@" 2>&1 >&3)"
    retval=$?
    [ -z "$e" ] || set -e
    # if the command failed (returned a non-zero exit code)
    if [ $retval -gt 0 ]; then
        retstr="command '$*' failed: ${error:-} ($retval)"
        die "$retstr" "$retval"
    fi
    return "$retval"
}

# run an app's module
# usage: `run <module_name> [args ...]`
run()
{
    [ $# -lt 1 ] && die 'usage: `run <module_name> [args ...]`';
    local module_name="$1" cmdfile=''
    shift
    declare -a args=()
    [ $# -gt 0 ] && args=("$*");
    cmdfile="$(find_module "$module_name")"
    if [ -n "$cmdfile" ] && [ -f "$cmdfile" ]; then
        set +o history
        "$cmdfile" "${args[*]}"
        status=$?
        set -o history
        return $status
    fi
    warning "module '$module_name' not found"
    return 1
}

# load an app's library
# @see <http://stackoverflow.com/a/3524860/3592658>
# usage: `use <module_name>`
use()
{
    [ $# -lt 1 ] && die 'usage: use <module_name>';
    local module_name="$1" cmdfile
    shift
    cmdfile="$(find_module "$module_name")"
    if [ -n "$cmdfile" ] && [ -f "$cmdfile" ]; then
        $DEBUG && echo "> sourcing '$cmdfile'"
        source "$cmdfile" || error "sourcing '$cmdfile' failed";
        return $?;
    else
        return 1;
    fi
}

# write an error string on STDERR without exiting
# usage: `warning <string>`
warning()
{
    [ -n "$1" ] && echo "> $*" >&2
    return 0
}

#### Bash-Utils ENVIRONMENT ####

abs_dirname() {
    local cwd="$(pwd)"
    local path="$1"
    while [ -n "$path" ]; do
        cd "${path%/*}"; local name="${path##*/}"; path="$($(type -p greadlink readlink | head -1) "$name" || true)";
    done
    pwd
    cd "$cwd"
}
sourcename="$(basename "${BASH_SOURCE[0]}")"
libexecdir="$(abs_dirname "${BASH_SOURCE[0]}")"
readonly BASH_UTILS="${libexecdir}/bash-utils"
readonly BASH_UTILS_MODEL="${libexecdir}/${sourcename/-core/-model}"
readonly BASH_UTILS_ROOT="${libexecdir}/"
readonly BASH_UTILS_MODULES="${libexecdir}/bash-utils-modules/"

CMD_PROG="$(basename "$0")"
CMD_ROOT="$(abs_dirname "$0")"
CMD_OS="$(uname)"
CMD_HOST="$(hostname -f)"
CMD_USER="$(id -un)"
CMD_CWD="$(pwd)"
CMD_PID="$$"
CMD_CALL_ORIGINAL="$0 $*"
readonly  CMD_PROG CMD_ROOT CMD_OS CMD_HOST CMD_USER CMD_CWD CMD_PID CMD_CALL_ORIGINAL
export CMD_CALL=''
export PIPED_INPUT=''

# lib error codes
# Error codes in Bash must return an exit code between 0 and 255.
# In the library, to be conform with C/C++ programs, we will try to use codes from 80 to 120
# (error codes in C/C++ begin at 64 but the recent evolutions of Bash reserved codes 64 to 78).
readonly E_ERROR=90
readonly E_OPTS=81
readonly E_CMD=82
readonly E_PATH=83

# load defaults
source "$BASH_UTILS_ROOT"/bash-utils-lib
export PRELOAD=true
for f in "$BASH_UTILS_MODULES"/*; do
    [ -x "$f" ] && source "$f";
done
export PRELOAD=false

# the core always returns a no-error status
##@!@##
[ "$(basename "$0")" = "$(basename "${BASH_SOURCE[0]}")" ] && exit 0 || return 0;
# vim: autoindent tabstop=4 shiftwidth=4 expandtab softtabstop=4 filetype=sh
